/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Levchuk
 */
public class FirstCar extends javax.swing.JPanel {

	/**
	 * Creates new form FirstCar
	 */
	public FirstCar() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		nameB = new javax.swing.JButton();
		backB = new javax.swing.JButton();
		useB = new javax.swing.JButton();
		rarrowB = new javax.swing.JButton();

		jButton1.setText("jButton1");

		setMaximumSize(new java.awt.Dimension(1000, 700));
		setMinimumSize(new java.awt.Dimension(1000, 700));
		setPreferredSize(new java.awt.Dimension(1000, 700));

		nameB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/anistonbd4.png"));
		nameB.setBorderPainted(false);
		nameB.setContentAreaFilled(false);
		nameB.setFocusPainted(false);
		nameB.setFocusable(false);
		nameB.setIconTextGap(0);
		nameB.setMaximumSize(new java.awt.Dimension(453, 38));
		nameB.setMinimumSize(new java.awt.Dimension(453, 38));
		nameB.setPreferredSize(new java.awt.Dimension(453, 38));

		backB.setBorderPainted(false);
		backB.setContentAreaFilled(false);
		backB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/backSmall.png"));
		backB.setFocusPainted(false);
		backB.setFocusable(false);
		backB.setIconTextGap(0);
		backB.setMaximumSize(new java.awt.Dimension(120, 120));
		backB.setMinimumSize(new java.awt.Dimension(120, 120));
		backB.setPreferredSize(new java.awt.Dimension(120, 120));
		backB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				backBMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				backBMouseExited(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				backBMousePressed(evt);
			}
		});

		useB.setBorderPainted(false);
		useB.setContentAreaFilled(false);
		useB.setFocusPainted(false);
		useB.setFocusable(false);
		useB.setIconTextGap(0);
		useB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/equipsmall.gif"));
		useB.setMaximumSize(new java.awt.Dimension(453, 50));
		useB.setMinimumSize(new java.awt.Dimension(453, 50));
		useB.setPreferredSize(new java.awt.Dimension(453, 50));
		useB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				useBMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				useBMouseExited(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				useBMousePressed(evt);
			}
		});

		rarrowB.setBorderPainted(false);
		rarrowB.setContentAreaFilled(false);
		rarrowB.setFocusPainted(false);
		rarrowB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/rarrowsmall.png"));
		rarrowB.setFocusable(false);
		rarrowB.setIconTextGap(0);
		rarrowB.setMaximumSize(new java.awt.Dimension(90, 78));
		rarrowB.setMinimumSize(new java.awt.Dimension(90, 78));
		rarrowB.setPreferredSize(new java.awt.Dimension(90, 78));
		rarrowB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				rarrowBMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				rarrowBMouseExited(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				rarrowBMousePressed(evt);
			}
		});
		rarrowB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rarrowBActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(backB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(144, 144, 144)
								.addComponent(nameB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(271, 271, 271)
								.addComponent(useB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(40, 40, 40).addComponent(rarrowB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(146, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(0, 0, 0).addComponent(backB,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(48, 48, 48).addComponent(nameB,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(useB, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(61, 61, 61))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(rarrowB, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(53, 53, 53)))));
	}// </editor-fold>//GEN-END:initComponents

	private void backBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_backBMouseEntered
		bEnter();
		backB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/backBig.png"));
	}// GEN-LAST:event_backBMouseEntered

	private void backBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_backBMouseExited
		backB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/backSmall.png"));
	}// GEN-LAST:event_backBMouseExited

	private void equipS() {
		Clip clip2 = null;
		AudioInputStream audioInputStream = null;

		try {
			audioInputStream = AudioSystem.getAudioInputStream(
					new File(System.getProperty("user.dir") + "/src/sounds/CLANK!.wav").getAbsoluteFile());
		} catch (UnsupportedAudioFileException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2 = AudioSystem.getClip();
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2.open(audioInputStream);
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		clip2.start();
	}

	private void backBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_backBMousePressed
		Clip clip2 = null;
		AudioInputStream audioInputStream = null;

		try {
			audioInputStream = AudioSystem.getAudioInputStream(
					new File(System.getProperty("user.dir") + "/src/sounds/DONE.wav").getAbsoluteFile());
		} catch (UnsupportedAudioFileException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2 = AudioSystem.getClip();
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2.open(audioInputStream);
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		clip2.start();
		action();
	}// GEN-LAST:event_backBMousePressed

	public void action() {

	}

	private void useBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_useBMouseEntered
		bEnter();
		eAction();
		useB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/equipbig.gif"));
	}

	public void eAction() {

	}

	private void useBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_useBMouseExited
		useB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/equipsmall.gif"));
	}// GEN-LAST:event_useBMouseExited

	private void useBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_useBMousePressed
		equipS();
	}

	private void rarrowBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_rarrowBMouseEntered
		bEnter();
		rarrowB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/rarrowbig.png"));
	}// GEN-LAST:event_rarrowBMouseEntered

	private void rarrowBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_rarrowBMouseExited
		rarrowB.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/images/rarrowsmall.png"));
	}// GEN-LAST:event_rarrowBMouseExited

	private void bEnter() {
		Clip clip2 = null;
		AudioInputStream audioInputStream = null;

		try {
			audioInputStream = AudioSystem.getAudioInputStream(
					new File(System.getProperty("user.dir") + "/src/sounds/ESC.wav").getAbsoluteFile());
		} catch (UnsupportedAudioFileException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2 = AudioSystem.getClip();
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2.open(audioInputStream);
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		clip2.start();
	}

	private void rarrowBMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_rarrowBMousePressed
		Clip clip2 = null;
		AudioInputStream audioInputStream = null;

		try {
			audioInputStream = AudioSystem.getAudioInputStream(
					new File(System.getProperty("user.dir") + "/src/sounds/DONE.wav").getAbsoluteFile());
		} catch (UnsupportedAudioFileException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2 = AudioSystem.getClip();
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			clip2.open(audioInputStream);
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		clip2.start();
		rAction();
	}// GEN-LAST:event_rarrowBMousePressed

	public void rAction() {

	}

	private void rarrowBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rarrowBActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rarrowBActionPerformed

	private File backgroundSource = new File(System.getProperty("user.dir") + "/src/images/garage.jpg"),
			carSource = new File(System.getProperty("user.dir") + "/src/images/AnistonBD4-GTA2.png"),
			speedSource = new File(System.getProperty("user.dir") + "/src/images/speed.gif"),
			strengthSource = new File(System.getProperty("user.dir") + "/src/images/strength.gif"),
			barFSource = new File(System.getProperty("user.dir") + "/src/images/barF.png"),
			barESource = new File(System.getProperty("user.dir") + "/src/images/barE.png");
	private BufferedImage background, car, barF, barE, speed, strength;
	private int balance = 0;

	public void setBalance(int input) {
		balance = input;
	}

	public int getBalance() {
		return balance;
	}

	public void paintComponent(Graphics g) {
		try {
			background = ImageIO.read(backgroundSource);
		} catch (IOException ex) {
			Logger.getLogger(FirstCar.class.getName()).log(Level.SEVERE, null, ex);
		}
		g.drawImage(background, 0, 0, 1000, 700, null);
		try {
			car = ImageIO.read(carSource);
		} catch (IOException ex) {
			Logger.getLogger(FirstCar.class.getName()).log(Level.SEVERE, null, ex);
		}
		try {
			barF = ImageIO.read(barFSource);
		} catch (IOException ex) {
			Logger.getLogger(FirstCar.class.getName()).log(Level.SEVERE, null, ex);
		}
		try {
			barE = ImageIO.read(barESource);
		} catch (IOException ex) {
			Logger.getLogger(FirstCar.class.getName()).log(Level.SEVERE, null, ex);
		}
		try {
			speed = ImageIO.read(speedSource);
		} catch (IOException ex) {
			Logger.getLogger(FirstCar.class.getName()).log(Level.SEVERE, null, ex);
		}
		try {
			strength = ImageIO.read(strengthSource);
		} catch (IOException ex) {
			Logger.getLogger(FirstCar.class.getName()).log(Level.SEVERE, null, ex);
		}
		g.drawImage(car, 210, 170, 150, 300, null);
		g.drawImage(speed, 575, 170, null);
		g.drawImage(strength, 525, 270, null);
		g.drawImage(barF, 497, 218, null);
		g.drawImage(barE, 561, 218, null);
		g.drawImage(barE, 625, 218, null);
		g.drawImage(barE, 689, 218, null);
		g.drawImage(barE, 753, 218, null);
		g.drawImage(barF, 497, 318, null);
		g.drawImage(barE, 561, 318, null);
		g.drawImage(barE, 625, 318, null);
		g.drawImage(barE, 689, 318, null);
		g.drawImage(barE, 753, 318, null);
		g.setColor(Color.green);
		g.setFont(new Font("Century Gothic Bold", 28, 28));
		g.drawString("Balance:" + balance, 780, 50);

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton backB;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton nameB;
	private javax.swing.JButton rarrowB;
	private javax.swing.JButton useB;
	// End of variables declaration//GEN-END:variables
}
